// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: xoapi/xo.proto

package xoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kiss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Kiss) Reset() {
	*x = Kiss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xoapi_xo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kiss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kiss) ProtoMessage() {}

func (x *Kiss) ProtoReflect() protoreflect.Message {
	mi := &file_xoapi_xo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kiss.ProtoReflect.Descriptor instead.
func (*Kiss) Descriptor() ([]byte, []int) {
	return file_xoapi_xo_proto_rawDescGZIP(), []int{0}
}

func (x *Kiss) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_xoapi_xo_proto protoreflect.FileDescriptor

var file_xoapi_xo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x78, 0x6f, 0x61, 0x70, 0x69, 0x2f, 0x78, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x78, 0x6f, 0x61, 0x70, 0x69, 0x22, 0x1a, 0x0a, 0x04, 0x4b, 0x69, 0x73, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x76, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x32, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x78,
	0x6f, 0x61, 0x70, 0x69, 0x3b, 0x78, 0x6f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_xoapi_xo_proto_rawDescOnce sync.Once
	file_xoapi_xo_proto_rawDescData = file_xoapi_xo_proto_rawDesc
)

func file_xoapi_xo_proto_rawDescGZIP() []byte {
	file_xoapi_xo_proto_rawDescOnce.Do(func() {
		file_xoapi_xo_proto_rawDescData = protoimpl.X.CompressGZIP(file_xoapi_xo_proto_rawDescData)
	})
	return file_xoapi_xo_proto_rawDescData
}

var file_xoapi_xo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xoapi_xo_proto_goTypes = []interface{}{
	(*Kiss)(nil), // 0: xoapi.Kiss
}
var file_xoapi_xo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xoapi_xo_proto_init() }
func file_xoapi_xo_proto_init() {
	if File_xoapi_xo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xoapi_xo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kiss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xoapi_xo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xoapi_xo_proto_goTypes,
		DependencyIndexes: file_xoapi_xo_proto_depIdxs,
		MessageInfos:      file_xoapi_xo_proto_msgTypes,
	}.Build()
	File_xoapi_xo_proto = out.File
	file_xoapi_xo_proto_rawDesc = nil
	file_xoapi_xo_proto_goTypes = nil
	file_xoapi_xo_proto_depIdxs = nil
}
